POST http://localhost:4100/
Content-Type: application/json

{
    "Title": "Code",
    "Content": "I will code",
    "createAt": "1/2/2023"
}


### GET ALL Notes
GET http://localhost:4100/
Content-Type: application/json

### Gettinhg note by id
GET http://localhost:4100/notes
content-Type: application/json


### UPDATE Notes DETAILS
PUT http://localhost:4100/notes/update
Content-Type: application/json

{

}

### DELETE USER
DELETE http://localhost:4100/notes/delete
Content-Type: application/json

